chunkBuster:
  item:
    type: END_PORTAL_FRAME
    name: "&5&l[ &e&lCHUNK BUSTER &5&l]"
    glow: true
    lore:
      - "&7Place this block in the chunk"
      - "&7that you wish to bust."

ecoCost: 500.00

whiteListedBlocks:
  - "SPAWNER"
  - "BEDROCK"
  - "BEACON"
  - "CHEST"
  - "TRAPPED_CHEST"
  - "HOPPER"

gui:
  title: "&aConfirm ChunkBust"

# If this is set to "true", every block in the chunk will be checked for WG claims
# Note: If a chunk buster is placed in a chunk the player cannot build in, it will be blocked regardless of what this is set as.
# This is only useful if you might have WG regions that might be incomplete chunks OR not sky to bedrock
extraWorldGuardCheck: true

factions:
  # Prevent chunk busting in "wilderness"
  blockWilderness: true
  # Minimum role to chunk bust in faction territory.
  # Possible roles are: ADMIN, COLEADER, MODERATOR, NORMAL, and RECRUIT.
  minimumRoleRequired: MODERATOR