# These values make up the chunk buster item
chunkBuster:
  item:
    type: END_PORTAL_FRAME
    name: "&5&l[ &e&lCHUNK BUSTER &5&l]"
    glow: true
    lore:
      - "&7Place this block in the chunk"
      - "&7that you wish to bust."

# This is how much is costs to use a chunk buster
# (Note: This relies on Vault)
ecoCost: 500.00

# These blocks will not be destroyed by a chunk buster
whiteListedBlocks:
  - "SPAWNER"
  - "BEDROCK"
  - "BEACON"
  - "CHEST"
  - "TRAPPED_CHEST"
  - "HOPPER"

# This is the configuration that represents the GUI
# that appears when a chunk buster is placed.
gui:
  title: "&aConfirm ChunkBust"
  size: 27
  inventory:
    allLevelsButton:
      item: FEATHER
      slot: 11
      name: "&bBust All Levels"
      lore:
        - "&7Click here to destroy ALL"
        - "&7y-levels in this chunk."
    belowLevelsButton:
      item: WOODEN_SHOVEL
      slot: 13
      name: "&bBust Lower Levels"
      lore:
        - "&7Click here to destroy blocks in this chunk, at"
        - "&7the y-level this buster was placed at and below."
    exitButton:
      item: BARRIER
      slot: 15
      name: "&cCancel"
      lore: {}
    filler:
      item: WHITE_STAINED_GLASS_PANE
      name: " "
      lore: {}

# If this is set to "true", every block in the chunk will be checked for WG claims
# Note: If a chunk buster is placed in a chunk the player cannot build in, it will be blocked regardless of what this is set as.
# This is only useful if you might have WG regions that might be incomplete chunks OR not sky to bedrock
extraWorldGuardCheck: true

# Set this to true to prevent Chunk Busters from being placed if another player is in the same chunk
blockIfOtherPlayersInChunk: true

factions:
  # Prevent chunk busting in "wilderness"
  blockWilderness: true
  # Minimum role to chunk bust in faction territory.
  # Possible roles are: ADMIN, COLEADER, MODERATOR, NORMAL, and RECRUIT.
  minimumRoleRequired: MODERATOR